general_url = 'https://********.********.****/api/'
user = "********"
password = "*********"
aragonstationstable = 'estaragon'
weatherforecasttable = 'weatherforecast'
weatherforecastdatatable = 'weatherforecastdata'
user_data = 1
data_resolution = 4
data_provider = 4
columnNameLon = 'long'
columnNameLat = 'lat'
hours = 'hourly'
time = 'time'
windspeed = 'windspeed_10m'
winddirection = 'winddirection_10m'
dewpoint = 'dewpoint_2m'
relativehumidity = 'relativehumidity_2m'
precipitation = 'precipitation'
directradiation = 'direct_radiation'
temperature = 'temperature_2m'
past_days = 2
loggingPath = 'log/log.log'
logger=None #Other injeced configs can define one
#DATABASE:
db_database='****'
db_user='******'
db_password='******'
db_host='artemisa.******.***'
db_port=*****
code=0
long=18
lat=19
file_system_prediction = 'log/dates_predictions.txt'